---
title: "Extracting_Herbivores"
author: "Jenn_McHenry"
date: "May 8, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(rfishbase)
library(sf)
library(rgdal)
library(maptools)
library(lubridate)
library(sp)
library(lubridate)
library(RchivalTag)
```


# Extracting Reference Information
```{r}
FIM_SQL_site_info=read.csv("data/Site_info_08_28_2018.csv")

FIM_Gear=read.csv("data/Gear_Types.csv");colnames(FIM_Gear)<-c("Gear","Gear_Description","Gear_Category")
Gear_info=read.csv(file = "data/Gear_info.csv");names(Gear_info)

#adding an effort column
FIM_Effort_Correction=plyr::join(FIM_SQL_site_info[c(2,9)],Gear_info,by="Reference",type="inner")
names(FIM_Effort_Correction)

#adding an effort column
FIM_Effort_Correction=plyr::join(FIM_Effort_Correction[c(1:2,5,7,11,13)],FIM_Gear,by="Gear",type="left",match="all")
names(FIM_Effort_Correction)

FIM_SQL_Gear_Corrected=FIM_Effort_Correction%>%
  dplyr::select(Reference,Gear,Wng_dpth,NetWidth,Soaktime,Dist_tow,Gear_Description,Gear_Category)%>%
  mutate(Wng_dpth=ifelse(Wng_dpth=="NULL",NA,Wng_dpth),NetWidth=ifelse(NetWidth=="NULL",NA,NetWidth),Soaktime=ifelse(Soaktime=="NULL",NA,Soaktime),Dist_tow=ifelse(Dist_tow=="NULL",NA,Dist_tow))%>%
  mutate(Effort=ifelse(Gear==300 | Gear==301 | Gear==306,((Dist_tow*4*1853)/100),ifelse(Gear==1 | Gear==2,0.3117,ifelse(Gear==5,0.11,ifelse(Gear==11 | Gear==13 | Gear==20 | Gear==21 | Gear==25 | Gear==26 | Gear==29 | Gear==100 | Gear==102 | Gear==103 | Gear==104 | Gear==105 | Gear==107 | Gear==107,1.4,ifelse(Gear==12 | Gear==22 | Gear==24 | Gear==27 | Gear==28,3.38,ifelse(Gear==10 | Gear==23,0.68,ifelse(Gear==160,41.20,ifelse(Gear==170,22.09,ifelse(Gear==180,4.65,ifelse(Gear==204 | Gear==205 | Gear==206 | Gear==207 | Gear==208 | Gear==209 | Gear==403 | Gear==404 | Gear==405 | Gear==406 | Gear==409 | Gear==410,NA,ifelse(Gear==350 | Gear==351 | Gear==354,1,NA))))))))))))


FL_Shoreline<-readShapePoly("C:/Users/jennm/Dropbox/GITHUB/Tropicalization/data/Florida_Shoreline.shp",proj4string = CRS("+proj=longlat +datum=WGS84"))

study_area<-readShapePoly("C:/Users/jennm/Dropbox/GITHUB/NASEM_Seagrass_EcosystemServices/Biodiversity_Data_Exploration/data/FWRI_FIM_SQL_Database_ALL/Florida_Gulf_Study_Area.shp",proj4string = CRS("+proj=longlat +datum=WGS84"))

Atlantic_study_area<-readShapePoly("C:/Users/jennm/Dropbox/GITHUB/Tropicalization/data/Atlantic_Mask.shp",proj4string = CRS("+proj=longlat +datum=WGS84"))


# #plotting all sites
# plot(FIM_SQL_site_info$Longitude,FIM_SQL_site_info$Latitude)
# plot(study_area,add=TRUE)


#Fixing the vegetation and shoreline information. 
FIM_SQL_site_info_fixed<-FIM_SQL_site_info%>%
  filter(Latitude>=20)%>%
  mutate(BottomVegCover=ifelse(BottomVegCover=="." | BottomVegCover=="", NA , as.character(BottomVegCover)),BottomVegCover2=as.integer(BottomVegCover),BottomVegCover3=ifelse(BottomVegCover2>101,NA,as.integer(BottomVegCover2)))%>%
  mutate(BottomVegCover=ifelse(BottomVegCover3>100,NA,BottomVegCover3))%>%
  mutate(ShoreDistance=ifelse(ShoreDistance=="." | ShoreDistance=="", NA , as.character(ShoreDistance)),ShoreDistance2=as.integer(ShoreDistance))%>%
  mutate(ShoreDistance=ShoreDistance2)%>%
  mutate(Vegetated=ifelse(BottomVegCover3>0,1,ifelse(BottomVegCover3==0,0,NA)))%>%
  dplyr::select(-BottomVegCover2,-BottomVegCover3,-ShoreDistance2)


Atlantic_study_area<-readShapePoly("C:/Users/jennm/Dropbox/GITHUB/Tropicalization/data/Atlantic_Mask.shp",proj4string = CRS("+proj=longlat +datum=WGS84"))


# #plotting all sites
plot(FIM_SQL_site_info_fixed$Longitude,FIM_SQL_site_info_fixed$Latitude,color="red")
plot(FL_Shoreline,add=TRUE)
plot(Atlantic_study_area,add=TRUE)


#clipping out sites that are on the east coast of FL
coordinates(FIM_SQL_site_info_fixed) <- ~Longitude+Latitude
proj4string(FIM_SQL_site_info_fixed)<- "+proj=longlat +datum=WGS84"
proj4string(study_area)<- "+proj=longlat +datum=WGS84"

FIM_SQL_site_info_clip <- FIM_SQL_site_info_fixed[study_area, ]
FIM_SQL_site_info_clipAtlantic <- FIM_SQL_site_info_fixed[Atlantic_study_area, ]


#Western Florida Gulf Coast
FIM_SQL_site_info_clip<-as.data.frame(FIM_SQL_site_info_clip)
summary((FIM_SQL_site_info_clip$BottomVegCover))

 
#Atlantic Florida Coast
FIM_SQL_site_info_clipAtlantic<-as.data.frame(FIM_SQL_site_info_clipAtlantic)
summary((FIM_SQL_site_info_clipAtlantic$BottomVegCover))



#Parsing out the most standardized datasets between 1997 to 2017  for the GUlf side
FIM_SQL_site_info_1997_2017<-FIM_SQL_site_info_clip%>%
  dplyr::select(TripID,Reference,Sampling_Date,Gear,Project_1,Project_2,Project_3,Station_1,Station_2,Station_3,Stratum,Rep,Longitude,Latitude,StartDepth, Secchi_on_bottom, Secchi_depth, Sediment_Depth, SAM,BottomVegCover,Vegetated,Seagrass_habitat_descriptor,Distance_to_edge,TotalShoreCover,Dist_to_Shore,Dist_to_MHTM)%>%
  mutate(Sampling_Date=as_date(Sampling_Date))%>%
  mutate(month=months(Sampling_Date),day=day(Sampling_Date),year=year(Sampling_Date))%>%
  mutate(month=factor(month,levels = c("January","February","March","April","May","June","July","August","September","October","November","December")),Seagrass_habitat_descriptor=as.factor(Seagrass_habitat_descriptor))%>%
  filter(year >= 1997)%>%
  filter(is.na(Longitude)!=TRUE)%>%
  filter(Longitude < 0.00 | Latitude > 0.00)%>%
  # filter(Project_1=="AM" | Project_2=="AM" | Project_3=="AM" | Project_1=="AS" | Project_2=="AS" | Project_3=="AS"| Project_1=="WI" | Project_2=="WI" | Project_3=="WI" | Project_1=="AR" | Project_2=="AR" | Project_3=="AR" | Project_1=="AK" | Project_2=="AK" | Project_3=="AK" | Project_1=="AI" | Project_2=="AI" | Project_3=="AI" | Project_1=="WO" | Project_2=="WO" | Project_3=="WO" | Project_1=="WS" | Project_2=="WS" | Project_3=="WS")%>%
  droplevels()%>%
  filter(Rep==1)

summary(FIM_SQL_site_info_1997_2017$BottomVegCover)
summary(FIM_SQL_site_info_1997_2017$StartDepth)
summary(FIM_SQL_site_info_1997_2017$SAM)




#Parsing out the most standardized datasets between 1997 to 2017 for the Atlantic side
FIM_SQL_site_info_1997_2017_Atlantic<-FIM_SQL_site_info_clipAtlantic%>%
  dplyr::select(TripID,Reference,Sampling_Date,Gear,Project_1,Project_2,Project_3,Station_1,Station_2,Station_3,Stratum,Rep,Longitude,Latitude,StartDepth, Secchi_on_bottom, Secchi_depth, Sediment_Depth, SAM,BottomVegCover,Vegetated,Seagrass_habitat_descriptor,Distance_to_edge,TotalShoreCover,Dist_to_Shore,Dist_to_MHTM)%>%
  mutate(Sampling_Date=as_date(Sampling_Date))%>%
  mutate(month=months(Sampling_Date),day=day(Sampling_Date),year=year(Sampling_Date))%>%
  mutate(month=factor(month,levels = c("January","February","March","April","May","June","July","August","September","October","November","December")),Seagrass_habitat_descriptor=as.factor(Seagrass_habitat_descriptor))%>%
  filter(year >= 1997)%>%
  filter(is.na(Longitude)!=TRUE)%>%
  filter(Longitude < 0.00 | Latitude > 0.00)%>%
  # filter(Project_1=="AM" | Project_2=="AM" | Project_3=="AM" | Project_1=="AS" | Project_2=="AS" | Project_3=="AS"| Project_1=="WI" | Project_2=="WI" | Project_3=="WI" | Project_1=="AR" | Project_2=="AR" | Project_3=="AR" | Project_1=="AK" | Project_2=="AK" | Project_3=="AK" | Project_1=="AI" | Project_2=="AI" | Project_3=="AI" | Project_1=="WO" | Project_2=="WO" | Project_3=="WO" | Project_1=="WS" | Project_2=="WS" | Project_3=="WS")%>%
  droplevels()%>%
  filter(Rep==1)

summary(FIM_SQL_site_info_1997_2017$BottomVegCover)
summary(FIM_SQL_site_info_1997_2017$StartDepth)
summary(FIM_SQL_site_info_1997_2017$SAM)


# #plotting all sites
# plot(FIM_SQL_site_info_1997_2017$Longitude,FIM_SQL_site_info_1997_2017$Latitude)
# plot(study_area,add=TRUE)

#Joining gear and effort information Gulf Side
FIM_SQL_site_info_1997_2017_GearEffort=plyr::join(FIM_SQL_site_info_1997_2017[c(-4)],FIM_SQL_Gear_Corrected[c(1:2,7:9)],by="Reference",type="left")


#Joining gear and effort information Atlantic Side
FIM_SQL_site_info_1997_2017_GearEffort_Atlantic=plyr::join(FIM_SQL_site_info_1997_2017_Atlantic[c(-4)],FIM_SQL_Gear_Corrected[c(1:2,7:9)],by="Reference",type="left")


names(FIM_SQL_Gear_Corrected)
levels(droplevels(as.factor(FIM_SQL_site_info_1997_2017_GearEffort$Gear_Category)))
levels(droplevels(as.factor(FIM_SQL_site_info_1997_2017_GearEffort$Gear_Description)))

names(FIM_SQL_Gear_Corrected)
levels(droplevels(as.factor(FIM_SQL_site_info_1997_2017_GearEffort_Atlantic$Gear_Category)))
levels(droplevels(as.factor(FIM_SQL_site_info_1997_2017_GearEffort_Atlantic$Gear_Description)))
```

# Species List
```{r}
species_list=read.csv("C:/Users/jennm/Dropbox/GITHUB/NASEM_Seagrass_EcosystemServices/Biodiversity_Data_Exploration/data/FWRI_FIM_SQL_Database_ALL/Species_list_queried08282018.csv")
names(species_list)

species_fields=load_taxa(species_list=species_list$Scientificname)
colnames(species_fields)[2]<-c("Scientificname")
names(species_fields)

species_diet=diet(species_list=species_list$Scientificname)
names(species_diet)
head(species_diet)
species_diet=species_diet%>%
  dplyr::select(SpecCode,Species,Troph,seTroph)%>%
  dplyr::filter(is.na(Troph)==FALSE)%>%
  dplyr::group_by(Species)%>%
  dplyr::summarize(Troph=mean(Troph,na.rm=TRUE))%>%
  dplyr::mutate(Scientificname=Species)%>%
  dplyr::select(-Species)
  

species_ecology=ecology(species_list=species_list$Scientificname)
names(species_ecology)
species_ecology=species_ecology%>%
  dplyr::select(SpecCode,Species,DietTroph,DietSeTroph)%>%
  dplyr::filter(is.na(DietTroph)==FALSE)%>%
  dplyr::group_by(Species)%>%
  dplyr::summarize(DietTroph=mean(DietTroph,na.rm=TRUE))%>%
  dplyr::mutate(Scientificname=Species)%>%
  dplyr::select(-Species)
  
  

species_ecosystem=ecosystem(species_list=species_list$Scientificname)
names(species_ecosystem)
head(species_ecosystem)

species_ecosystem=species_ecosystem%>%
  dplyr::select(Species,Climate,Polar,Boreal,Temperate,Subtropical)

species_ecosystem=species_ecosystem[complete.cases(species_ecosystem),]
names(species_ecosystem)
species_ecosystem=species_ecosystem%>%
  dplyr::group_by(Species)%>%
  dplyr::summarize(Polar=sum(Polar,na.rm=TRUE),Boreal=sum(Boreal,na.rm=TRUE),Temperate=sum(Temperate,na.rm=TRUE),Subtropical=sum(Subtropical,na.rm=TRUE))%>%
  dplyr::mutate(Scientificname=Species)%>%
  dplyr::select(-Species)
  

#Finalizing the species lists
species_list_modified=plyr::join(species_fields,species_list[c(1,4:5)],by="Scientificname",type="left")

species_list_modified=plyr::join(species_list_modified,species_diet,by="Scientificname",type="left")

species_list_modified=plyr::join(species_list_modified,species_ecology,by="Scientificname",type="left")

species_list_modified=plyr::join(species_list_modified,species_ecosystem,by="Scientificname",type="left")

species_list_modified=as.data.frame(species_list_modified)%>%
  dplyr::filter(Commonname!=".")%>%
  dplyr::select(-1,-3,-4,-8)%>%
  mutate(Scientificname=as.factor(Scientificname),Family=as.factor(Family),Order=as.factor(Order),Class=as.factor(Class))
  # dplyr::filter(is.na(DietTroph)!=TRUE)

species_list_modified=as.data.frame(species_list_modified)

summary(species_list_modified)

```


##Loading the abundance data
```{r}
#Species Abundance information
FIM_SQL_Species_N=read.csv("C:/Users/jennm/Dropbox/GITHUB/NASEM_Seagrass_EcosystemServices/Biodiversity_Data_Exploration/data/FWRI_FIM_SQL_Database_ALL/Species_abundance_queried09112018.csv")
# summary(FIM_SQL_Species_N)
names(FIM_SQL_Species_N)
head(FIM_SQL_Species_N)
str(FIM_SQL_Species_N)
# 

FIM_Species_Abundance=FIM_SQL_Species_N%>%
  dplyr::select(Reference,Species_record_id,NODCCODE,Number)%>%
  mutate(NODCCODE=as.factor(NODCCODE))%>%
  group_by(Reference,NODCCODE)%>%
  dplyr::summarize(Number=sum(Number))


Parrotfish=species_list_modified%>%
  filter(Family=="Scaridae")


Parrotfish_Abund=plyr::join(as.data.frame(Parrotfish),as.data.frame(FIM_Species_Abundance),by="NODCCODE",type="left")


FIM_Species_Abundance_1997_2017=plyr::join(FIM_SQL_site_info_1997_2017_GearEffort,FIM_Species_Abundance,by="Reference",type="inner")


FIM_Species_Abundance_1997_2017_Atlantic=plyr::join(FIM_SQL_site_info_1997_2017_GearEffort_Atlantic,FIM_Species_Abundance,by="Reference",type="inner")


##correcting the gear information for the GUlf side 
FIM_Species_Abundance_1997_2017_modified=FIM_Species_Abundance_1997_2017%>%
  mutate(Latitudinal_Bin=ifelse(Latitude<=26,"25-26",ifelse(Latitude<=27 & Latitude>26,"26-27",ifelse(Latitude<=28 & Latitude>27,"27-28",ifelse(Latitude<=29 & Latitude>28,"28-29",ifelse(Latitude<=30 & Latitude>29,"29-30",">30"))))))%>%
  droplevels()%>%
  filter(Gear_Description!="183m terminal bag purse seine")%>%
  filter(Gear_Description!="547m nylon trammel net with 117mm stretch mesh inner wall and 330mm stretch mesh outer walls.  Net used in directed redfish study.  Net Not Set.")%>%
  filter(Gear_Description!="547m nylon trammel net with 117mm stretch mesh inner wall and 330mm stretch mesh outer walsl.  Net used in directed redfish study.  Blind Set.")%>%
  filter(Gear_Description!="Hook and Line")%>% #removing hook and line
  filter(Gear_Description!="No Set")%>% #removing "no set" hauls
  mutate(Gear_Description=ifelse(Gear_Description=="183m center-bag seine","183m seine",ifelse(Gear_Description=="21.3 center-bag seine","21.3m seine",ifelse(Gear_Description=="21.3m center-bag seine","21.3m seine", ifelse(Gear_Description=="366m monofilament trammel net. 2.4m deep","366m monofilament trammel net",ifelse(Gear_Description=="547m nylon trammel net with 117mm stretch mesh inner wall and 330mm stretch mesh outer walls.  Net used in directed redfish study.","547m nylon trammel net", ifelse(Gear_Description=="6.1m otter trawl w/ 3.1mm liner & tickler chain.  A straight tow.","6.1m otter trawl",ifelse(Gear_Description=="6.1m otter trawl w/ 3.1mm liner & tickler chain.  An arc tow.","6.1m otter trawl", ifelse(Gear_Description=="61m center-bag seine","61m seine", ifelse(Gear_Description=="9.1-m center bag seine","9.1m seine", ifelse(Gear_Description=="Hook and line","Hook and line", ifelse(Gear_Description=="Offshore purse seine with spotter planes to collect adult Red Drum","Offshore Purse Seine",ifelse(Gear_Description=="Nylon trammel net 273m - Blind set.  Used for directed red drum hatchery project.  Fall 2000","273m nylon trammel net",ifelse(Gear_Description=="Nylon trammel net 273m - Normal set.  Used for directed red drum hatchery project Fall 2000","273m nylon trammel net","No Set"))))))))))))))%>%
  mutate(Gear_Description=as.factor(Gear_Description))%>%
  droplevels()
names(FIM_Species_Abundance_1997_2017_modified)

FIM_Species_Abundance_1997_2017_modified=plyr::join(FIM_Species_Abundance_1997_2017_modified,species_list_modified,by="NODCCODE",type="inner")

names(FIM_Species_Abundance_1997_2017_modified)
levels(FIM_Species_Abundance_1997_2017_modified$Gear_Description)
levels(FIM_Species_Abundance_1997_2017_modified$Commonname)


levels(droplevels(FIM_Species_Abundance_1997_2017_Atlantic$Gear_Description))
##correcting the gear information for the Atlantic side 
FIM_Species_Abundance_1997_2017_Atlantic_modified=FIM_Species_Abundance_1997_2017_Atlantic%>%
  mutate(Latitudinal_Bin=ifelse(Latitude<=26,"25-26",ifelse(Latitude<=27 & Latitude>26,"26-27",ifelse(Latitude<=28 & Latitude>27,"27-28",ifelse(Latitude<=29 & Latitude>28,"28-29",ifelse(Latitude<=30 & Latitude>29,"29-30",">30"))))))%>%
  droplevels()%>%
  mutate(Gear_Description=ifelse(Gear_Description=="183m center-bag seine","183m seine",ifelse(Gear_Description=="21.3 center-bag seine","21.3m seine",ifelse(Gear_Description=="21.3m center-bag seine","21.3m seine", ifelse(Gear_Description=="6.1m otter trawl w/ 3.1mm liner & tickler chain.  A straight tow.","6.1m otter trawl",ifelse(Gear_Description=="6.1m otter trawl w/ 3.1mm liner & tickler chain.  An arc tow.","6.1m otter trawl", ifelse(Gear_Description=="198m large mesh gillnet with five panels: 15m of 50mm mesh (# 139 twine)","198m gillnet",ifelse(Gear_Description=="198m large mesh gillnet with five panels: 15m of 50mm mesh (#139 twine)","198m gillnet",ifelse(Gear_Description=="40m center-bag seine","40m seine",ifelse(Gear_Description=="61m center-bag seine","61m seine",ifelse(Gear_Description=="Electrofishing","Electrofishing","No Set")))))))))))%>%
  mutate(Gear_Description=as.factor(Gear_Description))%>%
  filter(Gear_Description!="Electrofishing")%>% #removing hook and line
  filter(Gear_Description!="No Set")%>% #removing "no set" hauls
  droplevels()
names(FIM_Species_Abundance_1997_2017_modified)
levels(droplevels(FIM_Species_Abundance_1997_2017_Atlantic_modified$Gear_Description))


FIM_Species_Abundance_1997_2017_Atlantic_modified=plyr::join(FIM_Species_Abundance_1997_2017_Atlantic_modified,species_list_modified,by="NODCCODE",type="inner")
```

#Manipulating a final dataset from the Gulf Coast
```{r}
FIM_Species_Abundance_Tibble_1997_2017=as_data_frame(FIM_Species_Abundance_1997_2017_modified)

print(FIM_Species_Abundance_Tibble_1997_2017)

summary(FIM_Species_Abundance_Tibble_1997_2017$Number)

Top_Species_Overall_By_Gear=FIM_Species_Abundance_Tibble_1997_2017%>%
  dplyr::select(NODCCODE,Commonname,Number,Gear_Description,Latitudinal_Bin,Troph,BottomVegCover)%>%
  dplyr::group_by(NODCCODE,Commonname,Gear_Description)%>%
  dplyr::summarize(Total_Count=sum(Number,na.rm = TRUE))%>%
  dplyr::arrange(desc(Total_Count))%>%
  tidyr::spread(key=Gear_Description,value=Total_Count)


print(Top_Species_Overall_By_Gear)

Top_Species_Overall_By_Gear_Trophic_Levels=plyr::join(as.data.frame(Top_Species_Overall_By_Gear),species_list_modified[c(5,2,4:7,9:12)],by=c("NODCCODE","Commonname"),type="left")
write.csv(Top_Species_Overall_By_Gear_Trophic_Levels,file="output_tables//Top_Species_Overall_ByGearType.csv")


Top_Species_Overall_By_LatitudeBin=FIM_Species_Abundance_Tibble_1997_2017%>%
  dplyr::select(NODCCODE,Commonname,Number,Gear_Description,Latitudinal_Bin,Troph,BottomVegCover)%>%
  dplyr::group_by(NODCCODE,Commonname,Latitudinal_Bin)%>%
  dplyr::summarize(Total_Count=sum(Number,na.rm = TRUE))%>%
  dplyr::arrange(desc(Total_Count))%>%
  tidyr::spread(key=Latitudinal_Bin,value=Total_Count)

print(Top_Species_Overall_By_LatitudeBin)

Top_Species_Overall_By_LatitudeBin_Trophic_Levels=plyr::join(as.data.frame(Top_Species_Overall_By_LatitudeBin),species_list_modified[c(5,2,4:7,9:12)],by=c("NODCCODE","Commonname"),type="left")

write.csv(Top_Species_Overall_By_LatitudeBin_Trophic_Levels,file="output_tables/Top_Species_Overall_ByLatitudeBin.csv")
```


#Manipulating a final dataset from the Atlantic Coast
```{r}
FIM_Species_Abundance_Tibble_1997_2017_Atlantic=as_data_frame(FIM_Species_Abundance_1997_2017_Atlantic_modified)


plot(FIM_Species_Abundance_Tibble_1997_2017_Atlantic$Longitude,FIM_Species_Abundance_Tibble_1997_2017_Atlantic$Latitude)
plot(FL_Shoreline,add=TRUE)


print(FIM_Species_Abundance_Tibble_1997_2017_Atlantic)

summary(FIM_Species_Abundance_Tibble_1997_2017_Atlantic$Number)

Top_Species_Overall_By_Gear_Atlantic=FIM_Species_Abundance_Tibble_1997_2017_Atlantic%>%
  dplyr::select(NODCCODE,Commonname,Number,Gear_Description,Latitudinal_Bin,Troph,BottomVegCover)%>%
  dplyr::group_by(NODCCODE,Commonname,Gear_Description)%>%
  dplyr::summarize(Total_Count=sum(Number,na.rm = TRUE))%>%
  tidyr::spread(key=Gear_Description,value=Total_Count)



print(Top_Species_Overall_By_Gear_Atlantic)

Top_Species_Overall_By_Gear_Atlantic_Trophic_Levels=plyr::join(as.data.frame(Top_Species_Overall_By_Gear_Atlantic),species_list_modified[c(5,2,4:7,9:12)],by=c("NODCCODE","Commonname"),type="left")
write.csv(Top_Species_Overall_By_Gear_Atlantic_Trophic_Levels,file="output_tables/Top_Species_Overall_ByGearType_Atlantic.csv")


Top_Species_Overall_By_LatitudeBin_Atlantic=FIM_Species_Abundance_Tibble_1997_2017_Atlantic%>%
  dplyr::select(NODCCODE,Commonname,Number,Gear_Description,Latitudinal_Bin,Troph,BottomVegCover)%>%
  dplyr::group_by(NODCCODE,Commonname,Latitudinal_Bin)%>%
  dplyr::summarize(Total_Count=sum(Number,na.rm = TRUE))%>%
  dplyr::arrange(desc(Total_Count))%>%
  tidyr::spread(key=Latitudinal_Bin,value=Total_Count)

print(Top_Species_Overall_By_LatitudeBin_Atlantic)

Top_Species_Overall_By_LatitudeBin_Atlantic_Trophic_Levels=plyr::join(as.data.frame(Top_Species_Overall_By_LatitudeBin_Atlantic),species_list_modified[c(5,2,4:7,9:12)],by=c("NODCCODE","Commonname"),type="left")

write.csv(Top_Species_Overall_By_LatitudeBin_Atlantic_Trophic_Levels,file="output_tables/Top_Species_Overall_ByLatitudeBin_Atlantic.csv")
```


#Extracting the hydrological time-series from the GUlf side
```{r}
FIM_SQL_Hydro_info=read.csv("data/HydroLab_info_queried08292018.csv")
names(FIM_SQL_Hydro_info)


FIM_SQL_Hydro_Profile=plyr::join(FIM_SQL_site_info_1997_2017[c(2:3)],FIM_SQL_Hydro_info,by="Reference",type="left",match="all")
colnames(FIM_SQL_Hydro_Profile)[2]<-c("date")

#selecting bottom values only 
FIM_SQL_Hydro_Bottom_info=FIM_SQL_Hydro_info%>%
  group_by(Reference)%>%
  slice(which.max(Depth))

#selecting surface values only 
FIM_SQL_Hydro_Surface_info=FIM_SQL_Hydro_info%>%
  group_by(Reference)%>%
  slice(which.min(Depth))

#renaming so that data can be joined
colnames(FIM_SQL_Hydro_Surface_info)<-c("Reference","Surface_Depth","Beg_end","Surface_Temperature","Surface_Conductivity","Surface_pH","Surface_Salinity","Surface_DissolvedO2","Flagged_Surface_Value")
FIM_SQL_Hydro_Surface_info=FIM_SQL_Hydro_Surface_info[c(-3)] ## removing Beg_end value
colnames(FIM_SQL_Hydro_Bottom_info)<-c("Reference","Bottom_Depth","Beg_end","Bottom_Temperature","Bottom_Conductivity","Bottom_pH","Bottom_Salinity","Bottom_DissolvedO2","Flagged_Bottom_Value")
FIM_SQL_Hydro_Bottom_info=FIM_SQL_Hydro_Bottom_info[c(-3)] ## removing Beg_end value
# 

FIM_SQL_Hydro_Bottom_info=plyr::join(FIM_SQL_site_info_1997_2017[c(2)],FIM_SQL_Hydro_Bottom_info,by="Reference",type="left")
FIM_SQL_Hydro_Surface_info=plyr::join(FIM_SQL_site_info_1997_2017[c(2:4,13:14)],FIM_SQL_Hydro_Surface_info,by="Reference",type="left")

FIM_Temperature_TS_1997_2017=plyr::join(FIM_SQL_Hydro_Surface_info,FIM_SQL_Hydro_Bottom_info,by="Reference")
head(FIM_Temperature_TS_1997_2017)

FIM_Temperature_TS_1997_2017=FIM_Temperature_TS_1997_2017%>%
    mutate(Latitudinal_Bin=ifelse(Latitude<=26,"25-26",ifelse(Latitude<=27 & Latitude>26,"26-27",ifelse(Latitude<=28 & Latitude>27,"27-28",ifelse(Latitude<=29 & Latitude>28,"28-29",ifelse(Latitude<=30 & Latitude>29,"29-30",">30"))))))%>%
    droplevels()
write.csv(FIM_Temperature_TS_1997_2017,file = "output_tables/FIM_Temperature_TS_1997_2017.csv")
```

#Extracting Pinfish Data from the Gulf side
```{r}
names(FIM_Species_Abundance_1997_2017_modified)
head(FIM_Species_Abundance_1997_2017_modified)

names(FIM_Species_Abundance_1997_2017_modified)[6]<-c("depth")

FIM_Pinfish_Abundance=FIM_Species_Abundance_1997_2017_modified%>%
  filter(NODCCODE=="8835430201")%>%
  select(Reference,Sampling_Date,Gear_Description,Longitude,Latitude,depth,BottomVegCover,Vegetated,Number,Effort)%>%
  mutate(Number_pertow=Number,Number_per100sqm=Number/Effort)%>%
  select(-Number)
summary(FIM_Pinfish_Abundance)

write.csv(FIM_Pinfish_Abundance,file="output_tables/FIM_Pinfish_Abundance_TimeSeries.csv")
```



# pulling together DEP data
```{r}
FDEP=read.csv("C:/Users/jennm/Dropbox/PROJECTS/NAS_Seagrass_Project/Data/RAW/Seagrass_Groundtruthing_Data_Scoping/Florida_DEP_Aquatic_Preserve/CombinedMonitoring_FDEP_APP.csv")
names(FDEP)
summary(FDEP)
levels(FDEP$Region)

FDEP=FDEP%>%
  mutate(BraunBlanquet=Coverage,Blade_Length_Avg_cm=NA,Blade_Width_Avg_cm=NA,Shoots.per.m2=NA)%>%
  select(Month,Year,Region,Station,Latitude,Longitude,Replicate,Species,BraunBlanquet,Scallops,Urchins,Grass.or.Algae,Total.SAV,Total.Grass,Total.macroAlgae,Epipyhte.Denstiy,Blade_Length_Avg_cm,Blade_Width_Avg_cm,Shoots.per.m2,Sediment.type)

##aquiring SJB shoot and blade length info
SJB_Species=read.csv("C:/Users/jennm/Dropbox/PROJECTS/NAS_Seagrass_Project/Data/RAW/Seagrass_Groundtruthing_Data_Scoping/Florida_DEP_Aquatic_Preserve/St_Joes_Bay/FDEP_SJB_Species.csv")
names(SJB_Species)
head(SJB_Species)

SJB_Abiotic=read.csv("C:/Users/jennm/Dropbox/PROJECTS/NAS_Seagrass_Project/Data/RAW/Seagrass_Groundtruthing_Data_Scoping/Florida_DEP_Aquatic_Preserve/St_Joes_Bay/FDEP_SJB_Abiotic.csv")
names(SJB_Abiotic)
head(SJB_Species)

SJB_Species_fixed=plyr::join(SJB_Abiotic[1:5],SJB_Species,by=c("Station","Date","Time"))

SJB_Species_fixed=SJB_Species_fixed%>%
  mutate(Date=mdy(Date),Month=month(Date),Year=year(Date),Region=c("St Joe Bay"),Latitude=Fixed.Latitude,Longitude=Fixed.Longitude,Replicate=Quad)%>%
  rowwise()%>%
  mutate(Blade_Length_Avg_cm=mean(Blade_Length,Blade_Length.1,Blade_Length.2,Blade_Length.3, Blade_Length.4,na.rm=TRUE),Blade_Width_Avg_cm=mean(Blade_Width,Blade_Width.1,Blade_Width.2,Blade_Width.3,Blade_Width.4,na.rm=TRUE),Total.SAV=NA,Total.Grass=NA,Total.macroAlgae=NA,Sediment.type=NA,Grass.or.Algae=NA,Shoots.per.m2=NA)%>%
  select(Month,Year,Region,Station,Latitude,Longitude,Replicate,Species,BraunBlanquett,Scallops,Urchins,Grass.or.Algae,Total.SAV,Total.Grass,Total.macroAlgae,EpiphyteDensity,Blade_Length_Avg_cm,Blade_Width_Avg_cm,Shoots.per.m2,Sediment.type)

names(SJB_Species_fixed)
names(FDEP)



Estero=read.csv("C:/Users/jennm/Dropbox/PROJECTS/NAS_Seagrass_Project/Data/RAW/Seagrass_Groundtruthing_Data_Scoping/Florida_DEP_Aquatic_Preserve/Estero_Bay/DEP_Estero_Bay_Seagarss.csv")
names(Estero)
head(Estero)

Estero_fixed=Estero%>%
  mutate(Date=mdy(Date),Month=month(Date),Year=year(Date),Region=c("Estero Bay"),Replicate=Station,Station=Site,Latitude=NA,Longitude=NA,BraunBlanquet=Species.Abundance..BB.,Total.SAV=Total.Abundance..BB.,Scallops=NA,Urchins=NA,Total.Grass=NA,Total.macroAlgae=NA,Grass.or.Algae=NA,Urchins=NA,Scallops=NA,Blade_Length_Avg_cm=Blade.Length.Avg..cm.,Blade_Width_Avg_cm=NA,Sediment.type=Sediment)%>%
  select(Month,Year,Region,Station,Latitude,Longitude,Replicate,Species,BraunBlanquet,Scallops,Urchins,Grass.or.Algae,Total.SAV,Total.Grass,Total.macroAlgae,Epiphyte.Density,Blade_Length_Avg_cm,Blade_Width_Avg_cm,Shoots.per.m2,Sediment.type)

names(Estero_fixed)
names(FDEP)

#making sure that the dataframes have the same columsn
colnames(Estero_fixed)<-colnames(FDEP)
colnames(SJB_Species_fixed)<-colnames(FDEP)



##Stacking DEP datsets together
FDEP_ALL=rbind.data.frame(FDEP,Estero_fixed)
FDEP_ALL=rbind.data.frame(FDEP_ALL,SJB_Species_fixed)


#Making sure that the factor levels are consistent
names(FDEP_ALL)


FDEP_ALL_Fixed=FDEP_ALL%>%
  filter(is.na(Year)==FALSE)%>%
  filter(Species!="." & Species!="" & Species!="No Cover" & Species!="D")%>%
  mutate(Month=as.character(Month),Month=ifelse(Month=="AUGUST","August",ifelse(Month=="JULY","July",ifelse(Month=="July ","July",ifelse(Month=="JUNE","June",ifelse(Month=="MAY","May",ifelse(Month=="OCTOBER","October",ifelse(Month=="SEPTEMBER","September",ifelse(Month=="August ","August",Month)))))))))%>%
  mutate(Species=as.character(Species),Species=ifelse(Species=="drift","DRIFT",ifelse(Species=="HWRI ","HWRI",ifelse(Species=="HNIC","HINC",ifelse(Species=="a-Caulerpa prolifera","CPRO",ifelse(Species==" SFIL","SFIL",ifelse(Species=="Caulerpa prolifera","CPRO",ifelse(Species=="a-Caulerpa mexicana","CMEX",ifelse(Species=="a-Caulerpa serituloides","CSER",ifelse(Species=="Unknown","UID",ifelse(Species=="Thalassia","TTES",ifelse(Species=="Syringodium","SFIL",ifelse(Species=="Sargassum buxifolium","SBUX",ifelse(Species=="a-Caulerpa spp.","CXXX",ifelse(Species=="Caulerpa spp.","CXXX",ifelse(Species=="Drift","DRIFT",ifelse(Species=="Halodule","HWRI",ifelse(Species=="Halophila","HXXX",ifelse(Species=="HWIR","HWRI",ifelse(Species=="PCAD","PCAP",ifelse(Species=="Ruppia","RMAR",ifelse(Species=="Unknown Red Algae","UID",ifelse(Species=="Vallisneria","VSPI",ifelse(Species=="Hydrilla","HVER",ifelse(Species=="SARG","SBUX",Species)))))))))))))))))))))))))%>%
  filter(BraunBlanquet!="NGIQ")%>%
  mutate(BraunBlanquet=as.character(BraunBlanquet),BraunBlanquet=ifelse(BraunBlanquet=="",NA,ifelse(BraunBlanquet==".",NA,BraunBlanquet)))%>%
  mutate(Scallops=as.character(Scallops),Scallops=ifelse(Scallops=="",NA,ifelse(Scallops==".",NA,ifelse(Scallops==" ",NA,Scallops))))%>%
  mutate(Urchins=as.character(Urchins),Urchins=ifelse(Urchins=="",NA,ifelse(Urchins==".",NA,ifelse(Urchins==" ",NA,Urchins))))%>%
  mutate(Grass.or.Algae=as.character(Grass.or.Algae),Grass.or.Algae=ifelse(Grass.or.Algae=="",NA,ifelse(Grass.or.Algae==".",NA,ifelse(Grass.or.Algae=="Algae","ALGAE",ifelse(Grass.or.Algae=="Grass","GRASS",ifelse(Grass.or.Algae=="NGIQ",NA,Grass.or.Algae))))))%>%
  mutate(Total.SAV=as.character(Total.SAV),Total.SAV=ifelse(Total.SAV=="",NA,ifelse(Total.SAV==".",NA,Total.SAV)))%>%
    mutate(Total.Grass=as.character(Total.Grass),Total.Grass=ifelse(Total.Grass=="",NA,ifelse(Total.Grass==".",NA,ifelse(Total.Grass==",",NA,Total.Grass))))%>%
    mutate(Total.macroAlgae=as.character(Total.macroAlgae),Total.macroAlgae=ifelse(Total.macroAlgae=="",NA,ifelse(Total.macroAlgae==".",NA,ifelse(Total.macroAlgae==",",NA,ifelse(Total.macroAlgae==". ",NA,ifelse(Total.macroAlgae==" ",NA,Total.macroAlgae))))))%>%
    mutate(Epipyhte.Denstiy=as.character(Epipyhte.Denstiy),Epipyhte.Denstiy=ifelse(Epipyhte.Denstiy=="",NA,ifelse(Epipyhte.Denstiy==".",NA,ifelse(Epipyhte.Denstiy=="Clean","CLEAN",ifelse(Epipyhte.Denstiy=="Clean ","CLEAN",ifelse(Epipyhte.Denstiy=="Heavy","HEAVY",ifelse(Epipyhte.Denstiy=="Heavy ","HEAVY",ifelse(Epipyhte.Denstiy=="HEAVY ","HEAVY",ifelse(Epipyhte.Denstiy=="LGHT","LIGHT",ifelse(Epipyhte.Denstiy=="LGIHT","LIGHT",ifelse(Epipyhte.Denstiy=="Light","LIGHT",ifelse(Epipyhte.Denstiy=="Light ","LIGHT",ifelse(Epipyhte.Denstiy=="LIGHT ","LIGHT",ifelse(Epipyhte.Denstiy=="Moderatae","MODERATE",ifelse(Epipyhte.Denstiy=="moderate","MODERATE",ifelse(Epipyhte.Denstiy=="Moderate ","MODERATE",ifelse(Epipyhte.Denstiy=="MODERATE ","MODERATE",ifelse(Epipyhte.Denstiy=="Modetate","MODERATE",ifelse(Epipyhte.Denstiy=="N/A",NA,ifelse(Epipyhte.Denstiy=="1-Clean","CLEAN",ifelse(Epipyhte.Denstiy=="2-Light","LIGHT",ifelse(Epipyhte.Denstiy=="3-Moderate","MODERATE",ifelse(Epipyhte.Denstiy=="4-Heavy","HEAVY",ifelse(Epipyhte.Denstiy=="H","HEAVY",ifelse(Epipyhte.Denstiy=="L","Light",ifelse(Epipyhte.Denstiy=="M","MODERATE",ifelse(Epipyhte.Denstiy=="CLEAN ","CLEAN",ifelse(Epipyhte.Denstiy=="LiGHT","LIGHT",ifelse(Epipyhte.Denstiy=="Moderate","MODERATE",ifelse(Epipyhte.Denstiy=="Moderatte","MODERATE",ifelse(Epipyhte.Denstiy=="Light","LIGHT",Epipyhte.Denstiy)))))))))))))))))))))))))))))))%>%
  mutate(Grass.or.Algae=ifelse(Species=="TTES","Seagrass",ifelse(Species=="HWRI","Seagrass",ifelse(Species=="RMAR","Seagrass",ifelse(Species=="SFIL","Seagrass",ifelse(Species=="HENG","Seagrass",ifelse(Species=="HXXX","Seagrass","Algae")))))))%>%
  droplevels()


summary(as.factor(FDEP_ALL_Fixed$Month))
summary(FDEP_ALL_Fixed$Year)
summary(FDEP_ALL_Fixed$Station)
summary(as.factor(FDEP_ALL_Fixed$Species))
summary(as.factor(FDEP_ALL_Fixed$BraunBlanquet))
summary(as.factor(FDEP_ALL_Fixed$Scallops))
summary(as.factor(FDEP_ALL_Fixed$Urchins))
summary(as.factor(FDEP_ALL_Fixed$Grass.or.Algae))
summary(as.factor(FDEP_ALL_Fixed$Total.SAV))
summary(as.factor(FDEP_ALL_Fixed$Total.Grass))
summary(as.factor(FDEP_ALL_Fixed$Total.macroAlgae))
summary(as.factor(FDEP_ALL_Fixed$Epipyhte.Denstiy))
summary((FDEP_ALL_Fixed$Blade_Length_Avg_cm))
summary((FDEP_ALL_Fixed$Blade_Width_Avg_mm))
summary((FDEP_ALL_Fixed$Shoots.per.m2))
summary(as.factor(FDEP_ALL_Fixed$Sediment.type))


write.csv(FDEP_ALL_Fixed,file="output_tables/Combined_FDEP_AquaticPreserves_SeagrassData.csv")


```
